[Feature] 11주차 문제풀이 (~10.5)
yesl-kim/algorithm-python pull request #10
Opened 2023-10-06 04:04 UTC by yesl-kim

@f-lab-jake

2023-10-06 04:33 UTC, f-lab-jake requested changes

2023-10-06 04:33 UTC, f-lab-jake commented on 실전풀이/바탕화면 정리/solution.py
> +         for j in range(len(wallpaper[0])):
`enumerate`를 쓰고 인덱스 참조를 줄여봅시다

2023-10-06 04:33 UTC, f-lab-jake commented on 실전풀이/소수찾기/solution.py
> +            return False
`i*i > num` 조건 추가합시다.

2023-10-09 03:42 UTC, yesl-kim commented on 실전풀이/바탕화면 정리/solution.py
> +         for j in range(len(wallpaper[0])):
넵 058cb4261fdc5b9b8aefac28d4d475f446f73f4c

2023-10-09 03:43 UTC, yesl-kim commented on 실전풀이/소수찾기/solution.py
> +            return False
아하, 넵 f958baae89f63574a11bceb774d59e9c66c95661

2023-10-10 03:34 UTC, f-lab-jake approved these changes

2023-10-13 00:36 UTC, merged