[Feature] 2주차 문제풀이
yesl-kim/algorithm-python pull request #2
Opened 2023-08-10 10:49 UTC by yesl-kim

2023-08-17 03:44 UTC, f-lab-jake requested changes

2023-08-17 03:44 UTC, f-lab-jake commented on 실전풀이/build-array-from-permutation/solution.py
> +            ans[i]=nums[nums[i]]
`ans`의 변경을 줄일 수 있습니다.

2023-08-17 03:44 UTC, f-lab-jake commented on 실전풀이/remove-duplicates-from-sorted-array/solution.py
> +        for i in range(1,len(nums)):
인덱스 안쓰는 방식으로도 한번 해보세요

2023-08-17 03:44 UTC, f-lab-jake commented on 실전풀이/plus-one/solution.py
> +            if i<0:
이부분을 반복문 밖에서 빼보세요.
그리고 digits를 처음에 뒤집어놓고 해보세요

2023-08-17 03:44 UTC, f-lab-jake commented on 실전풀이/maximum-subarray/solution.py
> +        sums=list(accumulate(nums))
잘 찾아서 썼습니다

2023-08-17 03:44 UTC, f-lab-jake commented on 실전풀이/maximum-subarray/solution.py
> +        for i in range(n):
인덱스 i를 쓰지않고 해보세요

2023-08-17 03:44 UTC, f-lab-jake commented on 실전풀이/merge-intervals/solution.py
> +        for i in range(1,len(intervals)):
인덱스를 쓰지 않고 해보세요.

그다음에 재귀호출로 바꾸어보세요.

2023-08-19 02:13 UTC, yesl-kim commented on 실전풀이/build-array-from-permutation/solution.py
> +            ans[i]=nums[nums[i]]
https://github.com/yesl-kim/algorithm-python/pull/2/commits/211c28e6e6086e8df2fdce2090f2398458d3b178#r1296639332

2023-08-19 02:14 UTC, yesl-kim commented on 실전풀이/maximum-subarray/solution.py
> +        for i in range(n):
수정했습니다! https://github.com/yesl-kim/algorithm-python/pull/2/commits/85a7be9996c71baa2a5bc4070c319eb818b6cee0

2023-08-20 02:22 UTC, yesl-kim commented on 실전풀이/merge-intervals/solution.py
> +        for i in range(1,len(intervals)):
인덱스 제거 - 3fc190314b51354adf0b61708f97b16b4e35c114
재귀 (인덱스 활용) - 2bf4b861a5aca2b8e8bff59c1ed78960eda55eb4
재귀 (이터레이터......를 써봤는데요..) - d8824ed2472f27e050a9c862502434883849d525

근데 동작이 acc를 다루는게 결국 reduce랑 비슷해서요 
reduce 사용 - 76384c763048a573f4968f5c8891ea7abf4aaa11

수정해보았습니다!

2023-08-21 23:14 UTC, yesl-kim commented on 실전풀이/remove-duplicates-from-sorted-array/solution.py
> +        for i in range(1,len(nums)):
수정했습니다! 044a50e5ddaf2c4c900f7bb840069181131f9b66

2023-08-23 01:53 UTC, yesl-kim commented on 실전풀이/plus-one/solution.py
> +            if i<0:
수정했습니다! d2d45da1dbdf00a6c87580ba41cc1f3b7e4bfbf0

digits을 먼저 뒤집으니 enumerate를 쓸 수 있어서 깔끔해보이는데,
reverse를 한 번 더 해줘야했어요
이게 맞나요..?

2023-08-23 03:16 UTC, f-lab-jake commented on 실전풀이/plus-one/solution.py
> +            if i<0:
네 한번더 뒤집는게 의도에 맞습니다. 비효율적으로 보일수있는데, 최적의 방법으로 동작하게 할 방법이 결국엔 있습니다.
그이전에 의미론적으로 낮은 자리가 앞으로 오는게 자연스럽기에 그렇게 하라고한거구요. 그 자연스러운 의미때문에 코드도 덩달아 깔끔해집니다.

그리고 `== 9` 란 조건문은 `+ 1`하는 동작과 커플링되어 있습니다.
그냥 `+ 1`을 먼저 해놓고 그게 10이 넘는지 확인하는게 낫습니다.
그러면 문제가 바뀌어서 `+3`으로 하라고 해도 한부분만 고쳐도되겠죠.
요런게 잘 드러나지 않는 커플링인데, 놓치지않고 제거하는게 중요합니다.

2023-08-24 04:22 UTC, yesl-kim commented on 실전풀이/plus-one/solution.py
> +            if i<0:
오아  ˙Ⱉ˙  
수정해보았습니다 02dbaddb6c9c760ec47b9b69eafb9ee602959dc3

reverse도 최적의 방법이 있다고 해서 한 번만 하게끔 해봤는데..
이러니 자연스럽지 않아졌죠..? 하하 힌트를 주실 수 있나요?

2023-08-26 02:51 UTC, f-lab-jake commented on 실전풀이/merge-intervals/solution.py
> +        def _merge(acc, it):
`acc`를 인자에서 빼보세요

2023-08-27 03:08 UTC, yesl-kim commented on 실전풀이/merge-intervals/solution.py
> +        def _merge(acc, it):
아...! 수정했습니다! 06458a23bcc3cf81906c913349e9ac83c892efc6

2023-08-27 03:41 UTC, bglgwyng commented on 실전풀이/plus-one/solution.py
> +            if i<0:
아 최적의 방법은 새로운 개념을 배운다음에 가능합니다. 이전에 고치신거까지가 현재로썬 최적입니다.

2023-09-04 06:38 UTC, f-lab-jake requested changes

2023-09-04 06:38 UTC, f-lab-jake commented on 실전풀이/merge-intervals/solution.py
> +            if len(intervals) == 1:
빈 `intervals`에 대한 처리도 추가해주세요

2023-09-06 05:15 UTC, f-lab-jake approved these changes
👍

2023-09-07 21:28 UTC, merged