[Feature] 6주차 문제풀이
yesl-kim/algorithm-python pull request #6
Opened 2023-08-31 07:50 UTC by yesl-kim

2023-09-07 02:17 UTC, f-lab-jake requested changes

2023-09-07 02:17 UTC, f-lab-jake commented on 레벨테스트/1-starter/1.py
> +                y += distance
좀더 잘짜봅시다

2023-09-07 02:17 UTC, f-lab-jake commented on 실전풀이/array-partition/array-partition.py
> +        return reduce(lambda acc, i: acc + min(nums[i], nums[i+1]), range(0, len(nums), 2), 0)
`zip(xs, xs[1:])` 을 활용해보세요

2023-09-07 02:17 UTC, f-lab-jake commented on 실전풀이/climbing-stairs/climbing-stairs.py
> +         return dp[n]
재귀로 풀어보세요.
성능이 안나온다면 왜 그런지 생각해보세요.

2023-09-07 02:17 UTC, f-lab-jake commented on 실전풀이/longest-palindromic-substring/longest-palindromic-substring.py
> +                         res = s[left: right + 1]
사소한데 가독성을 떨어트릴수있느 ㄴ부분입니다.
먼저 `s[left:right + 1]` 을 먼저 변수를 빼고 그거랑 길이를 비교해보세요

2023-09-07 02:17 UTC, f-lab-jake commented on 실전풀이/merge-two-sorted-list/merge-two-sorted-list.py
> +    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
재귀로도 해봅시다

2023-09-07 02:17 UTC, f-lab-jake commented on 실전풀이/search-in-rotated-sorted-array/search-in-rotated-sorted-array.py
> +            return -1
try except를 쓴 선택이 좋습니다

2023-09-07 02:17 UTC, f-lab-jake commented on 실전풀이/summary-range/summary-range.py
> +            if i + 1 == len(nums) or n + 1 != nums[i+1]:
for문에서 빼는게 좋은 패턴이죠

2023-09-07 02:17 UTC, f-lab-jake commented on 실전풀이/주차요금계산/주차요금계산.py
> +    if enters:
빼도 되지않나요?

2023-09-07 21:44 UTC, yesl-kim commented on 실전풀이/주차요금계산/주차요금계산.py
> +    if enters:
중간에 여러번 입출차를 할 수 있어서요-
그래도 빼도 되나요??

2023-09-08 01:37 UTC, yesl-kim commented on 실전풀이/summary-range/summary-range.py
> +            if i + 1 == len(nums) or n + 1 != nums[i+1]:
그렇담 재귀일까요??
일단 재귀로 수정해보았습니다 🤔47fba52e5d6e2a13fbfe6416f2ec5666cf34c67b

2023-09-08 01:37 UTC, yesl-kim commented on 실전풀이/merge-two-sorted-list/merge-two-sorted-list.py
> +    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
넵 ! a2d94cc288cb51ffd50c4e8f133dc9c060405d64

2023-09-08 05:21 UTC, bglgwyng requested changes

2023-09-08 05:21 UTC, bglgwyng commented on 실전풀이/주차요금계산/주차요금계산.py
> +    if enters:
`enters`가 빈 딕셔너리면 어차피 실행 안될거란 얘기였습니다

2023-09-08 05:21 UTC, bglgwyng commented on 실전풀이/summary-range/summary-range.py
> +            if i + 1 == len(nums) or n + 1 != nums[i+1]:
아 재귀가 아니라 for문에 딱한번만 조건문을 넣는게 좋지않습니다

2023-09-09 00:44 UTC, yesl-kim commented on 실전풀이/주차요금계산/주차요금계산.py
> +    if enters:
아ㅏ 입차만 하고 출차는 안할 수도 있어서요!

2023-09-10 02:44 UTC, yesl-kim commented on 실전풀이/climbing-stairs/climbing-stairs.py
> +         return dp[n]
오.. 전혀 메모를 사용하면 전혀 다를 게 없다고 생각했는데 차이가 있어서 놀랐어요
처음에는 흐름이 한 번 bottom을 찍고 올라오니까 더 오래 걸리는건가 했는데
재귀 호출의 오버헤드 때문이라는 말이 많았어요- 🤔

2023-09-10 02:45 UTC, yesl-kim commented on 실전풀이/climbing-stairs/climbing-stairs.py
> +         return dp[n]
f63deb28834d316d7042f90cc337ccc63f6da2b5

2023-09-10 02:45 UTC, yesl-kim commented on 실전풀이/array-partition/array-partition.py
> +        return reduce(lambda acc, i: acc + min(nums[i], nums[i+1]), range(0, len(nums), 2), 0)
9199ab4cd1155ef15fe8470c94f7db5ff1f6ec05 👀

2023-09-10 02:47 UTC, yesl-kim commented on 실전풀이/summary-range/summary-range.py
> +            if i + 1 == len(nums) or n + 1 != nums[i+1]:
아하 ! c06c6ba91dda3879d0a37fd0a3148d4c224805c6

2023-09-11 02:31 UTC, yesl-kim commented on 실전풀이/longest-palindromic-substring/longest-palindromic-substring.py
> +                         res = s[left: right + 1]
다시 보는데 저도 이해하기 힘들었네요,, 수정했습니다! 7158081ec7c687225fcada3597a84477f342e9a2 
수정하던 도중 길이 비교를 할 때 max함수로 바꿔봤는데 시간 차이가 꽤 나더라구요- (두배정도 👀)
max는 사전검색을 해서 그렇다고 하던데 잘 이해가 안가네요, 시간날 때 조금 보겠지만 
엄청 가독성이 좋아지는 게 아니라면 if 문을 쓰는게 좋은 걸까요?

2023-09-11 02:31 UTC, yesl-kim commented on 레벨테스트/1-starter/1.py
> +                y += distance
fd1e501e12651c0818a3f930996a3e2598d462ea

2023-09-11 02:35 UTC, f-lab-jake approved these changes

2023-09-11 02:35 UTC, f-lab-jake commented on 레벨테스트/1-starter/1.py
> +                break
바꿔도될지 확인하고 바꾸는거보다, 바꾸고나서 유효한지 확인하는 코드가 실수할 여지가 더 적고 읽기도 쉽습니다.
이번엔 이 패턴덕분에 일반화하기도 쉬웠죠

2023-09-11 02:40 UTC, f-lab-jake commented on 실전풀이/longest-palindromic-substring/longest-palindromic-substring.py
> +                         res = s[left: right + 1]
사실 max 썼다고 2배 느려지면 언어가(정환히 인터프리터 구현체가) 잘못하는 상황같네요.
그냥 평소에 max쓰시고 저걸로 전체프로그램이 엄청 느려지면 그때 눈물을 머금고 if로 바꾸면 될거같습니다.

2023-09-11 03:02 UTC, f-lab-jake commented on 실전풀이/주차요금계산/주차요금계산.py
> +    if enters:
`enters`가 빈 딕셔너리면 `enters.items()`가 빈 리스트가 나오지않나요?

2023-09-12 02:39 UTC, yesl-kim commented on 실전풀이/주차요금계산/주차요금계산.py
> +    if enters:
아아아 맙소사.. 그렇군요

2023-09-12 02:43 UTC, yesl-kim commented on 레벨테스트/1-starter/1.py
> +                break
아아 괜히 변수를 만들지 않으려고 했는데 그러네요
마음에 새기겠습니다..

2023-10-10 02:32 UTC, merged