[Feature] 9주차 문제풀이 (~9.20)
yesl-kim/algorithm-python pull request #8
Opened 2023-09-25 01:09 UTC by yesl-kim

@f-lab-jake

2023-10-04 15:16 UTC, f-lab-jake requested changes

2023-10-04 15:16 UTC, f-lab-jake commented on 실전풀이/add-two-numbers/add-two-numbers.py
> +                n1.next, n2.next = n2.next, n1.next
요부분을 빼봅시다.

2023-10-04 15:16 UTC, f-lab-jake commented on 실전풀이/add-two-numbers/add-two-numbers.py
> +        while n1:
여기서 `n1`말고 그냥 새로운 변수를 쓰는게 도움이 될겁니다

2023-10-04 15:16 UTC, f-lab-jake commented on 실전풀이/implement-trie-prefix-tree/implement-trie-prefix-tree.py
> +class Trie:
지금 구현한건 trie가 아닙니다. 시간초과가 나야 정상인데요. 통과한건가요?

2023-10-04 15:16 UTC, f-lab-jake commented on 실전풀이/시소짝꿍/solution.py
> +    return res
시소짝궁은 대칭적인 관계입니다. x가 y와 시소짝궁이면 y도 x와 시소짝궁입니다. 가령 배우자는 대칭적이지만, 부모/자식은 대칭적이지 않습니다.
이 성질을 이용해보세요.

2023-10-05 01:41 UTC, yesl-kim commented on 실전풀이/implement-trie-prefix-tree/implement-trie-prefix-tree.py
> +class Trie:
앗 넵 통과했길래 맞은 줄 알았는데, 스터디 들어가보니 전혀 아니더라구요
다시 구현해봤습니다!
2fdf4ddc1c07713b3da6d466f9d52c65a07df5c5

2023-10-07 04:15 UTC, f-lab-jake approved these changes

2023-10-09 03:23 UTC, merged