[Feature] 10주차 문제풀이 (~9/27)
yesl-kim/algorithm-python pull request #9
Opened 2023-10-01 04:28 UTC by yesl-kim

@f-lab-jake

2023-10-04 15:27 UTC, f-lab-jake requested changes

2023-10-04 15:27 UTC, f-lab-jake commented on 실전풀이/0128-longest-consecutive-sequence/0128-longest-consecutive-sequence.py
> +        return self.length(max(sequences.values(), key=self.length))
`self.length`가 두번쓰이는걸 피해보세요.

2023-10-04 15:27 UTC, f-lab-jake commented on 실전풀이/0295-find-median-from-data-stream/0295-find-median-from-data-stream.py
> +        return len(self.arr) % 2 == 0
굳이 안만들어도 되는 함수고, 또 만들겠다면 인자를 배열로 하는게 더 활용성이 높습니다.
클래스에 메소드를 추가할땐 클래스가 주는 맥락과 관련있는지 생각해보세요.

2023-10-04 15:27 UTC, f-lab-jake commented on 실전풀이/42747. H－Index/H－Index.py
> +    return res
꼭 이문제뿐 아니라, 이진탐색을 언제써도 되는지 일반적인 조건을 설명해보세요.

2023-10-07 02:14 UTC, yesl-kim commented on 실전풀이/0128-longest-consecutive-sequence/0128-longest-consecutive-sequence.py
> +        return self.length(max(sequences.values(), key=self.length))
아하 넵 e7e1b82571c76390937d6b4704b3df399cfbc2ac

2023-10-07 04:18 UTC, f-lab-jake approved these changes

2023-10-13 00:36 UTC, merged